### ISSUE TITLE
Ores are not being generated

### ISSUE THREAD

**Issue by Mewsalk** [HellBreecher/Arcanum#4] opened 2020-10-04 21:01 UTC
All the vanilla minecraft ores such as coal, iron, etc... are not being generated when this mod is on, most likely due to a mod conflict but I do not have any other mod that affects world generation other than Apotheosis

**Comment by HellBreecher** [comment] 2020-10-06 04:54
I've loaded a new world with the most recent public version of Arcanum installed. All vanilla ores are generating in the world at a normal rate. The issue may be caused by another mod. I'll be closing the issue. Feel free to join the discord https://discord.com/invite/dDHvtrR and under modded-minecraft share a list of the mods for your pack and I'll be more than happy to assist you in figuring out the problem. (At first you will only be able to talk in Lobby, but I'll have you pushed passed that pretty quick)

**Closed as completed** 2020-10-06 04:54 UTC
Labels: invalid
